name: ray_hanabi
dependencies:
- python=3.7.3
- pip
- setuptools
- pip:
  - requests
  - ray[rllib,debug]==0.8.0
  - tensorflow==1.15.0
  - git+https://github.com/deepmind/hanabi-learning-environment.git
  - google-api-python-client
  - gputil
  - cryptography
  - aiohttp
  - psutil
  - setproctitle