name: ray_hanabi
dependencies:
- python=3.7.3
- pip
- setuptools
- pip:
  - requests
  - resources/ray-0.8.0.dev7-cp37-cp37m-manylinux1_x86_64.whl[rllib,debug]
  - tensorflow==1.15.0
  - git+https://github.com/deepmind/hanabi-learning-environment.git
  - google-api-python-client
  - gputil
  - cryptography
  - aiohttp
  - psutil
  - setproctitle