name: ray_hanabi
dependencies:
- python=3.6.5
- pip
- setuptools
- pip:
  - ray[debug,rllib,dashboard,tune]
  - requests
  - tensorflow==1.15.0
  - git+https://github.com/carlbalmer/hanabi-learning-environment.git